language: scala
dist: xenial
sudo: false
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.12
    env: COV=false
  - jdk: openjdk11
    scala: 2.13.3
    env: COV=true
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "$HOME/.cache"
install:
- pip install --user codecov
script:
- |
  if [[ "${COV:-""}" = "true" ]]; then
    sbt ++$TRAVIS_SCALA_VERSION clean coverage scalafmtCheckAll scalafmtSbtCheck "scalafixAll --check" compile test:compile test coverageReport coverageOff && codecov
  else
    sbt ++$TRAVIS_SCALA_VERSION clean scalafmtCheckAll scalafmtSbtCheck "scalafix --check" compile test:compile test
  fi
- |
  if [[ $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
    openssl aes-256-cbc -K $encrypted_fecd5c9b735d_key -iv $encrypted_fecd5c9b735d_iv -in .travis/secret-key.asc.enc -out .travis/secret-key.asc -d
    echo "$PGP_PASSPHRASE" | gpg --passphrase-fd 0 --batch --yes --import .travis/secret-key.asc
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      command=
      if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        command="publishSigned"
      else
        if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
          command="publishLocalSigned"
        else
          command="publishLocal"
        fi
      fi
      sbt ++$TRAVIS_SCALA_VERSION ${command[@]}
    fi
  fi
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  slack:
    secure: hjNjVQOD5/vsaGded3GW2KuNvZ33wTn0cNHv0VWMpfmRnEmtDRDCJ4vezq829gIf1MqhUMwjcnjsfJFIHsrr6xSUQ5i8J451o5zX1tReSmfNBfkeUbnX8Z0gs20xgj/N/V9+PESzk+TBGaCbZfQAz8JFVf6GwmMbYIskj0X2sIxU46DpM/cQTR7U8pz+XsYzb6wtke6Ut8sT/4PIZ4aUS5hiBJ0bPUMo0BSMPM+EKEmIIuddNduJtVc9MV0A6U1v4B7PSiXYfFgbio8l3sancg/BcUxGR1C0QG8re8YhZSeDDDdl8E7uGQp6jD8TKdSlat/hfKuqa3WrCjCDwPsrspHK8aYUdfGbucZunvPAnfv/6tPHKqtf+RYJaO8dFx0tB08jn8yql3Ydv9l4J8nObqt6jWlNXoPH/s/jGz41fFnh0GQsxDJYFBTEa1ochTwYDraDIMbxfhynsYNbbijpDfM+1w/+/pPjSBqOsxMO/9CMlWy3Nf/ueKnYgqsCYttIIAkXwzBUbDg8+IN1S+zM6MC+Ffl4oFY6XfRJr2T4QBkMNOC9WlHmLWDq3DsOlxMte80Ynm71Tk61J35UGTnlB/XvJM0tqDInahLZtSecUiXnu7oX3/osf22p6581zQILWrbcKilr6gvoo1eNwbCYbzEvIblD/CS59Z+NBuGyPAE=
