name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      scala-versions:  ${{ steps.set-scala-versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-scala-versions
        run: |
          scala212=$(grep "scala2.12" project/Dependencies.scala | sed -E 's/.*= //')
          scala213=$(grep "scala2.13" project/Dependencies.scala | sed -E 's/.*= //')
          scala3=$(grep "scala3" project/Dependencies.scala | sed -E 's/.*= //')
          echo "matrix={\"scalaVersion\": [${scala212}, ${scala213}, ${scala3}]}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.scala-versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt ++${{ matrix.scalaVersion }} test
        if: startsWith(matrix.scalaVersion, '3')
      - run: sbt ++${{ matrix.scalaVersion }} coverage test coverageReport
        if: ${{ !startsWith(matrix.scalaVersion, '3') }}
      - uses: codecov/codecov-action@v3
        if: ${{ !startsWith(matrix.scalaVersion, '3') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests
          fail_ci_if_error: true
          verbose: true
  post-build:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: ':'
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll
  scalafix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt "scalafixAll --check"
