name: Tagging

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: maven
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Setting up git config
        run: |
          git config --global user.name "trks"
          git config --global user.email "type.in.type@gmail.com"
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: sudo npm install -g standard-version
      - name: Generate tag and release body
        run: standard-version --infile RELEASE_BODY.md --skip.commit
      - name: Publish tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo "tag_name=$(git describe HEAD --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md
